import mongoose from 'mongoose';

const HomeContentSchema = new mongoose.Schema({
  destinations: {
    subtitle: { type: String, default: 'Oppdag verden med oss' },
    subtitleEn: { type: String },
    title: { type: String, default: 'Velg Din Neste Destinasjon' },
    titleEn: { type: String },
  },
  activities: {
    subtitle: { type: String, default: 'Ting å gjøre i Nepal' },
    subtitleEn: { type: String },
    title: { type: String, default: 'Eventyrlige Opplevelser' },
    titleEn: { type: String },
  },
  whoWeAre: {
    subtitle: { type: String, default: 'Hvem vi er' },
    subtitleEn: { type: String },
    title: { type: String, default: 'Eksperter på Himalaya Eventyr' },
    titleEn: { type: String },
    description: { type: String, default: 'Velkommen til Nepalvibb, et stolt datterselskap av Actual Adventure Pvt. Ltd. Med over 15 års dedikasjon har vi etablert oss som den fremste aktøren for skandinaviske reisende i Nepal.' },
    descriptionEn: { type: String },
    yearsOfExperience: { type: String, default: '15' },
    yearsOfExperienceLabel: { type: String, default: 'Års Erfaring' },
    yearsOfExperienceLabelEn: { type: String },
    image1: { type: String, default: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80' },
    image2: { type: String, default: 'https://images.unsplash.com/photo-1551882547-ff43c63faf76?auto=format&fit=crop&w=800&q=80' },
    feature1Title: { type: String, default: 'TRYGGHET' },
    feature1TitleEn: { type: String },
    feature1Desc: { type: String, default: 'Sikkerhet i fokus på alle turer.' },
    feature1DescEn: { type: String },
    feature2Title: { type: String, default: 'EKSPERTISE' },
    feature2TitleEn: { type: String },
    feature2Desc: { type: String, default: 'Lokale guider med dyp kunnskap.' },
    feature2DescEn: { type: String },
  },
  tours: {
    subtitle: { type: String, default: 'Våre Mest Populære Turer' },
    subtitleEn: { type: String },
    title: { type: String, default: 'Finn Ditt Perfekte Eventyr' },
    titleEn: { type: String },
  },
  purpose: {
    subtitle: { type: String, default: 'Vårt samfunnsansvar' },
    subtitleEn: { type: String },
    title: { type: String, default: 'En Reise med Formål: Ditt Eventyr – Deres Håp' },
    titleEn: { type: String },
    description: { type: String, default: 'Vi støtter lokale prosjekter for gatehunder i Nepal. Ved å reise med oss bidrar du direkte til å gi disse dyrene et bedre liv gjennom Actual Adventure Foundation.' },
    descriptionEn: { type: String },
    longDescription: { type: String, default: 'Actual Adventure Foundation er vår dedikerte stiftelse som arbeider for å forbedre livet til gatehunder i Nepal. Gjennom steriliseringsprogrammer, vaksinasjonskampanjer og bevisstgjøring i lokalsamfunn har vi hjulpet tusenvis av hunder. Hver reise du bestiller hos oss bidrar direkte til dette arbeidet.' },
    longDescriptionEn: { type: String },
    mission: { type: String, default: 'Vår misjon er å skape en bærekraftig fremtid for Nepals gatehunder gjennom medfølelse, handling og fellesskap.' },
    missionEn: { type: String },
    stats: { type: String, default: JSON.stringify([{ number: '2000+', label: 'Hunder sterilisert' }, { number: '5000+', label: 'Vaksinert' }, { number: '15+', label: 'Lokalsamfunn' }, { number: '10 år', label: 'Med innvirkning' }]) },
    statsEn: { type: String },
    images: { type: String, default: JSON.stringify(['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1551882547-ff43c63faf76?auto=format&fit=crop&w=800&q=80']) },
    buttonText: { type: String, default: 'Les mer om prosjektet' },
    buttonTextEn: { type: String },
    buttonLink: { type: String, default: '/om-prosjektet' },
    image: { type: String, default: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=80' },
    heroCta1Text: { type: String, default: 'Bli med' },
    heroCta1TextEn: { type: String },
    heroCta1Link: { type: String, default: '/plan-your-trip' },
    heroCta2Text: { type: String, default: 'Se resultater' },
    heroCta2TextEn: { type: String },
    heroCta2Link: { type: String, default: '#impact' },
    missionLabel: { type: String, default: 'Vår Misjon' },
    missionLabelEn: { type: String },
    missionCtaText: { type: String, default: 'Støtt saken' },
    missionCtaTextEn: { type: String },
    missionCtaLink: { type: String, default: '/plan-your-trip' },
    storyLabel: { type: String, default: 'Historien Vår' },
    storyLabelEn: { type: String },
    storyTitle: { type: String, default: 'Hvordan Det Hele Startet' },
    storyTitleEn: { type: String },
    featurePills: { type: String, default: JSON.stringify(['Gatehunder reddet', 'Lokalsamfunn', 'Bærekraft']) },
    featurePillsEn: { type: String },
    sinceText: { type: String, default: 'Siden 2015' },
    sinceTextEn: { type: String },
    sinceDesc: { type: String, default: '10+ år med innvirkning' },
    sinceDescEn: { type: String },
    impactLabel: { type: String, default: 'Vår Påvirkning' },
    impactLabelEn: { type: String },
    impactTitle: { type: String, default: 'Sammen Gjør Vi En Forskjell' },
    impactTitleEn: { type: String },
    howLabel: { type: String, default: 'Slik Fungerer Det' },
    howLabelEn: { type: String },
    howTitle: { type: String, default: 'Ditt Eventyr Gir Håp' },
    howTitleEn: { type: String },
    howDescription: { type: String, default: 'Hver reise du bestiller hos oss støtter direkte vårt arbeid for gatehunder i Nepal.' },
    howDescriptionEn: { type: String },
    steps: { type: String, default: JSON.stringify([
      { title: 'Book Din Reise', desc: 'Velg din drømmereise til Nepal. Hver bestilling teller.' },
      { title: 'Vi Donerer', desc: 'En del av reisens pris går direkte til Actual Adventure Foundation.' },
      { title: 'Sammen Skapes Endring', desc: 'Ditt valg gir gatehunder et bedre liv – og deg en uforglemmelig opplevelse.' }
    ]) },
    stepsEn: { type: String },
    galleryLabel: { type: String, default: 'Bildegalleri' },
    galleryLabelEn: { type: String },
    galleryTitle: { type: String, default: 'Prosjektet I Bilder' },
    galleryTitleEn: { type: String },
    galleryImages: { type: String, default: JSON.stringify([
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1551882547-ff43c63faf76?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80'
    ]) },
    ctaBadge: { type: String, default: 'Bli Med' },
    ctaBadgeEn: { type: String },
    ctaTitle: { type: String, default: 'Klar for å gjøre en {highlight}?' },
    ctaTitleEn: { type: String },
    ctaTitleHighlight: { type: String, default: 'forskjell' },
    ctaTitleHighlightEn: { type: String },
    ctaDescription: { type: String, default: 'Book din neste reise til Nepal. Opplev Himalaya, kulturen og naturen – og gi samtidig noe tilbake til lokalsamfunnene.' },
    ctaDescriptionEn: { type: String },
    ctaButtonText: { type: String, default: 'Planlegg Reisen' },
    ctaButtonTextEn: { type: String },
    ctaButtonLink: { type: String, default: '/plan-your-trip' },
    ctaSecondaryText: { type: String, default: 'Utforsk våre turer' },
    ctaSecondaryTextEn: { type: String },
    ctaSecondaryLink: { type: String, default: '/turer' },
  },
  testimonials: {
    subtitle: { type: String, default: 'Gjestevurderinger' },
    subtitleEn: { type: String },
    title: { type: String, default: 'Hva våre gjester sier' },
    titleEn: { type: String },
  },
  blog: {
    subtitle: { type: String, default: 'Tips og inspirasjon' },
    subtitleEn: { type: String },
    title: { type: String, default: 'Siste nyheter og artikler' },
    titleEn: { type: String },
  }
}, { timestamps: true });

export default mongoose.models.HomeContent || mongoose.model('HomeContent', HomeContentSchema);
